3.2.0 Release: Add gh release and pypi publish jobs. finish the pyproject.toml rewrites

diff --git a/.github/workflows/test-fast-pypi-release.yml b/.github/workflows/test-fast-pypi-release.yml
--- a/.github/workflows/test-fast-pypi-release.yml
+++ b/.github/workflows/test-fast-pypi-release.yml
@@ -14,25 +14,25 @@ jobs:
       version: ${{ steps.check.outputs.version }}
 
     steps:
-    - id: check
-      name: Check commit message
-      env:
-        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
-      run: |
-        echo "INFO: Commit message: $COMMIT_MESSAGE"
-        
-        regex="^([0-9]+\.[0-9]+\.[0-9]+) Release.*"
-        
-        if [[ $COMMIT_MESSAGE =~ $regex ]]; then 
-          echo "INFO: Pattern matched."
-          ver="${BASH_REMATCH[1]}"
-          echo "INFO: Version: $ver"
-          echo "status=success" >> $GITHUB_OUTPUT
-          echo "version=$ver" >> $GITHUB_OUTPUT
-        else
-          echo "INFO: Pattern doesn't match."
-          echo "status=fail" >> $GITHUB_OUTPUT
-        fi
+      - id: check
+        name: Check commit message
+        env:
+          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
+        run: |
+          echo "INFO: Commit message: $COMMIT_MESSAGE"
+          
+          regex="^([0-9]+\.[0-9]+\.[0-9]+) Release.*"
+          
+          if [[ $COMMIT_MESSAGE =~ $regex ]]; then 
+            echo "INFO: Pattern matched."
+            ver="${BASH_REMATCH[1]}"
+            echo "INFO: Version: $ver"
+            echo "status=success" >> $GITHUB_OUTPUT
+            echo "version=$ver" >> $GITHUB_OUTPUT
+          else
+            echo "INFO: Pattern doesn't match."
+            echo "status=fail" >> $GITHUB_OUTPUT
+          fi
 
   check-changelog-file:
     needs: check-commit-message
@@ -42,76 +42,116 @@ jobs:
     
     outputs:
       status: ${{ steps.check.outputs.status }}
+      changelog: ${{ steps.check.outputs.changelog }}
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@v3
+      - name: Checkout
+        uses: actions/checkout@v3
 
-    - id: check
-      name: Match version
-      run: |
-        echo "INFO: version: ${{ needs.check-commit-message.outputs.version }}"
-        
-        # Look for files in the "docs" folder with "changelog" in their name (ignore case)
-        files=$(find docs -iname "*changelog*")
-        echo "DEBUG: files: $files"
+      - id: check
+        name: Match versions
+        run: |
+          # Look for files in the "docs" folder with "changelog" in their name (ignore case)
+          files=$(find docs -iname "*changelog*")
+          echo "DEBUG: files: $files"
 
-        # Validation I: Only one changelog file should be in the "docs" folder
-        file_count=$(echo "$files" | wc -l)
-        echo "DEBUG: file_count: $file_count"
-        if [ "$file_count" -ne 1 ]; then
-          echo "ERROR: Multiple changelog files found in the "docs" folder."
-          exit 1
-        fi
+          # Validation I: Only one changelog file should be in the "docs" folder
+          file_count=$(echo "$files" | wc -l)
+          echo "DEBUG: file_count: $file_count"
+          if [ "$file_count" -ne 1 ]; then
+            echo "ERROR: Multiple changelog files found in the "docs" folder."
+            exit 1
+          fi
 
-        # Parse
-        text=$(cat "$files")
-        # echo "text: $text"
+          # Parse the changelog file
+          text=$(cat "$files")
+          # echo "DEBUG: text: $text"
 
-        # Latest
-        match=$(echo "$text" | grep -m 1 -Pzo "(?s)- \d+\.\d+\.\d+(.*?)\n-")
-        echo "match: '$match'"
+          # Parse the latest changelog
+          latest_changelog=$(echo "$text" | grep -m 1 -Pzo "(?s)- \d+\.\d+\.\d+(.*?)\n-")
+          echo "DEBUG: latest_changelog: '$latest_changelog'"
 
-        # Trim the ending "\n-" (the last 2 chars; '\n' counts as 1 char)
-        trimmed_match=${match%??}
-        echo "trimmed_match: '$trimmed_match'"
+          # Trim the ending "\n-" (the last 2 chars; '\n' counts as 1 char)
+          latest_changelog_trimmed=${latest_changelog%??}
+          echo "DEBUG: latest_changelog_trimmed: '$latest_changelog_trimmed'"
 
-        # Get the version from the changelog file
-        ver_from_changelog=$(echo "$trimmed_match" | grep -oP '\d+\.\d+\.\d+' | head -n 1)
-        echo "ver_from_changelog: '$ver_from_changelog'"
+          # Parse the version from the changelog file
+          ver_from_changelog=$(echo "$latest_changelog_trimmed" | grep -oP '\d+\.\d+\.\d+' | head -n 1)
+          echo "DEBUG: ver_from_changelog: '$ver_from_changelog'"
 
-        # Match the version
-        if [[ "${{ needs.check-commit-message.outputs.version }}" == "$ver_from_changelog" ]]; then
-            echo "INFO: Versions matched."
-            echo "status=success" >> $GITHUB_OUTPUT
-        else
-            echo "INFO: Versions don't match."
-            echo "status=fail" >> $GITHUB_OUTPUT
-        fi
+          # Match the versions
+          if [[ "${{ needs.check-commit-message.outputs.version }}" == "$ver_from_changelog" ]]; then
+              echo "INFO: Versions matched."
+              echo "status=success" >> $GITHUB_OUTPUT
+              echo "changelog=$latest_changelog_trimmed" >> $GITHUB_OUTPUT
+          else
+              echo "INFO: Versions don't match."
+              echo "status=fail" >> $GITHUB_OUTPUT
+          fi
 
-  update-pyproject-toml:
+  rewrite-pyproject-toml:
     needs: [check-commit-message, check-changelog-file]
     if: needs.check-changelog-file.outputs.status == 'success'
 
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@v3
+      - name: Checkout
+        uses: actions/checkout@v3
 
-    - name: Rewriting
-      run: |
-        echo "foo"
+      - name: Rewriting
+        run: |
+          sed -E -i "s/(version = \")[0-9]+\.[0-9]+\.[0-9]+/\1$version/" pyproject.toml
 
-  publish-to-PyPI:
-    needs: [check-commit-message, check-changelog-file, update-pyproject-toml]
+      - name: Commit
+        run: |
+          git config user.name "nvfp/fast-pypi-release"
+          git config user.email "foo@bar.baz"
+          git commit -am "Update version in pyproject.toml"
+          git push
+
+
+  create-gh-release:
+    needs: [check-commit-message, check-changelog-file, rewrite-pyproject-toml]
 
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@v3
+      - name: Checkout
+        uses: actions/checkout@v3
+    
+      - name: Release
+        uses: nvfp/gh-action-simple-release@1.4.0
+        env:
+          GH_TOKEN: ${{ github.token }}
+        with:
+          tag: ${{ needs.check-commit-message.outputs.version }}
+          desc: ${{ needs.check-changelog-file.outputs.changelog }}
 
-    - name: Publish
-      run: |
-        echo "bar"
+  publish-to-PyPI:
+    needs: [check-commit-message, check-changelog-file, rewrite-pyproject-toml]
+
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.7
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install build twine
+
+      - name: Build
+        run: python -m build
+
+      # - name: Publish
+      #   env:
+      #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
+      #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
+      #   run: twine upload dist/*
