47.11.0b0 release: testing!

diff --git a/.github/workflows/test-fast-pypi-release.yml b/.github/workflows/test-fast-pypi-release.yml
--- a/.github/workflows/test-fast-pypi-release.yml
+++ b/.github/workflows/test-fast-pypi-release.yml
@@ -51,13 +51,13 @@ jobs:
         with:
           fetch-depth: 0  # Fetch all tags
 
-      - name: Inspect Git tag
-        run: |
-          tag="${{ needs.check-commit-msg.outputs.ver }}"
-          if [[ -n $(git tag -l "$tag") ]]; then
-            echo "ERROR: Tag already exists: '$tag'"
-            exit 1
-          fi
+      # - name: Inspect Git tag
+      #   run: |
+      #     tag="${{ needs.check-commit-msg.outputs.ver }}"
+      #     if [[ -n $(git tag -l "$tag") ]]; then
+      #       echo "ERROR: Tag already exists: '$tag'"
+      #       exit 1
+      #     fi
 
       - name: Inspect PyPI version
         run: |
